### ISSUE TITLE
Is not work for wrapped function

### ISSUE THREAD

**Issue by artalar** [kentcdodds/preval.macro#1]
Hi! Thanks for this project.

I try to reuse preval.macro for injecting some additional logic, but precompile is not work in that case. [Check the example](https://codesandbox.io/s/try-to-wrap-prevalmacro-d8bd5)

```js
function test(...a) {
  // some computation...
  return preval(...a);
}

const oneByPreval = preval`module.exports = 1 + ${2} - 1 - 1`; // `1`
const oneByPrevalWrapper = test`module.exports = 1 + ${2} - 1 - 1`; // `{}`
```

**Comment by kentcdodds** [comment]
This is correct. It's a limitation of the compiler. You'll have to give another way to do what you're trying to do. Sorry.
